### ISSUE TITLE
Unable to enter ProfileSettings more than once

### ISSUE THREAD

**Issue by p-ranav** [Max-Mobility/permobil-client#104]
1. Start up the PushTracker Mobile App
2. Click Profile
3. Click the Profile Settings gear on the top right - This will work
4. Click the back button
5. Click the Profile Settings gear again - *This doesn't work*

You'll see this error in the terminal:

```bash
JS: ERROR Error: Uncaught (in promise): Error: Cannot reattach ActivatedRouteSnapshot created from a different route
JS: Error: Cannot reattach ActivatedRouteSnapshot created from a different route
JS:     at setFutureSnapshotsOfActivatedRoutes file:///node_modules/@angular/router/fesm5/router.js:1835:0
JS:     at setFutureSnapshotsOfActivatedRoutes file:///node_modules/@angular/router/fesm5/router.js:1842:0
JS:     at setFutureSnapshotsOfActivatedRoutes file:///node_modules/@angular/router/fesm5/router.js:1842:0
JS:     at setFutureSnapshotsOfActivatedRoutes file:///node_modules/@angular/router/fesm5/router.js:1842:0
JS:     at createNode file:///node_modules/@angular/router/fesm5/router.js:1823:0
JS:     at file:///node_modules/@angular/router/fesm5/router.js:1863:0
JS:     at Array.map (<anonymous>) [angular]
JS:     at createOrReuseChildren (file:///data/data/com.permobil.pushtracker/files/app/vendor.js:5188...
```

## Notes

1. This might require a RouteReuseStrategy implementation

**Comment by finger563** [comment]
as a note - this also affects the info pop-up on the home-tab.  After you leave the profile-settings page, if you then go to the home-tab and tap the info button, you'll see nothing and if you then hit the back button you'll get a similar error:
```
JS: Unhandled Promise rejection: Cannot reattach ActivatedRouteSnapshot created from a different route ; Zone: <root> ; Task: Promise.then ; Value: Error: Cannot reattach ActivatedRouteSnapshot created from a different route Error: Cannot reattach ActivatedRouteSnapshot created from a different route
JS:     at setFutureSnapshotsOfActivatedRoutes file:///node_modules/@angular/router/fesm5/router.js:1835:0
JS:     at setFutureSnapshotsOfActivatedRoutes file:///node_modules/@angular/router/fesm5/router.js:1842:0
JS:     at setFutureSnapshotsOfActivatedRoutes file:///node_modules/@angular/router/fesm5/router.js:1842:0
JS:     at setFutureSnapshotsOfActivatedRoutes file:///node_modules/@angular/router/fesm5/router.js:1842:0
JS:     at createNode file:///node_modules/@angular/router/fesm5/router.js:1823:0
JS:     at file:///node_modules/@angular/router/fesm5/router.js:1863:0
JS:     at Array.map (<anonymous>) [<roo...
```

**Comment by p-ranav** [comment]
Maybe the simplest solution is to change Profile Settings to be a modal, just like app-info
