### ISSUE TITLE
Exception thrown when returning from Activity tab to Home tab

### ISSUE THREAD

**Issue by p-ranav** [Max-Mobility/permobil-client#195]
```bash
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method destroyItem failed
System.err: Error: java.lang.IllegalStateException: Cannot detach Fragment attached to a different FragmentManager. Fragment FragmentBase_vendor_170467_32_TabFragmentImplementation{62f5ecc (932f1a79-324f-4a25-bddc-b07dbc229487) id=0x12 android:viewpager:18:0} is already attached to a FragmentManager.
System.err:     androidx.fragment.app.BackStackRecord.detach(BackStackRecord.java:221)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1109)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1089)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1081)
System.err:     com.tns.gen.androidx.viewpager.widget.PagerAdapter_vendor_170498_32_FragmentPagerAdapter.destroyItem(PagerAdapter_vendor_170498_32_FragmentPagerAdapter.java:45)
System.err:     androidx.viewpager.widget.ViewPager.dataSetChanged(ViewPager.java:1047)
System.err:     androidx.viewpager.widget.ViewPager$PagerObserver.onChanged(ViewPager.java:3097)
System.err:     androidx.viewpager.widget.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:291)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1109)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1089)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1081)
System.err:     com.tns.gen.androidx.fragment.app.DialogFragment_vendor_155759_26_DialogFragmentImpl.onDismiss(DialogFragment_vendor_155759_26_DialogFragmentImpl.java:25)
System.err:     android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1607)
System.err:     android.os.Handler.dispatchMessage(Handler.java:112)
System.err:     android.os.Looper.loop(Looper.java:216)
System.err:     android.app.ActivityThread.main(ActivityThread.java:7625)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
System.err: 
System.err: StackTrace:
System.err:     Frame: function:'FragmentPagerAdapter.destroyItem', file:'file:///node_modules/tns-core-modules/ui/tab-view/tab-view.js:122:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/tab-view/tab-view.js.TabView.setAdapterItems', file:'file:///node_modules/tns-core-modules/ui/tab-view/tab-view.js:492:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/tab-view/tab-view.js.TabView.onUnloaded', file:'file:///node_modules/tns-core-modules/ui/tab-view/tab-view.js:439:0
System.err:     Frame: function:'', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:315:77
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:304:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.callUnloaded', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:315:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.unloadView', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:444:0
System.err:     Frame: function:'', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:246:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView', file:'file:///node_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild', file:'file:///node_modules/tns-core-modules/ui/core/view/view-common.js:992:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.onUnloaded', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:245:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view/view.js.View.onUnloaded', file:'file:///node_modules/tns-core-modules/ui/core/view/view.js:279:0
System.err:     Frame: function:'', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:315:77
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:304:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.callUnloaded', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:315:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.unloadView', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:444:0
System.err:     Frame: function:'', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:246:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView', file:'file:///node_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild', file:'file:///node_modules/tns-core-modules/ui/core/view/view-common.js:992:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.onUnloaded', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:245:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view/view.js.View.onUnloaded', file:'file:///node_modules/tns-core-modules/ui/core/view/view.js:279:0
System.err:     Frame: function:'', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:315:77
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:304:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.callUnloaded', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:315:0
System.err:     Frame: function:'DialogFragmentImpl.onDismiss', file:'file:///node_modules/tns-core-modules/ui/core/view/view.js:163:0
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1109)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1089)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1081)
System.err:     at com.tns.gen.androidx.viewpager.widget.PagerAdapter_vendor_170498_32_FragmentPagerAdapter.destroyItem(PagerAdapter_vendor_170498_32_FragmentPagerAdapter.java:45)
System.err:     at androidx.viewpager.widget.ViewPager.dataSetChanged(ViewPager.java:1047)
System.err:     at androidx.viewpager.widget.ViewPager$PagerObserver.onChanged(ViewPager.java:3097)
System.err:     at androidx.viewpager.widget.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:291)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1109)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1089)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1081)
System.err:     at com.tns.gen.androidx.fragment.app.DialogFragment_vendor_155759_26_DialogFragmentImpl.onDismiss(DialogFragment_vendor_155759_26_DialogFragmentImpl.java:25)
System.err:     at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1607)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:112)
System.err:     at android.os.Looper.loop(Looper.java:216)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7625)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
System.err: Caused by: java.lang.IllegalStateException: Cannot detach Fragment attached to a different FragmentManager. Fragment FragmentBase_vendor_170467_32_TabFragmentImplementation{62f5ecc (932f1a79-324f-4a25-bddc-b07dbc229487) id=0x12 android:viewpager:18:0} is already attached to a FragmentManager.
System.err:     at androidx.fragment.app.BackStackRecord.detach(BackStackRecord.java:221)
System.err:     ... 24 more
JS: ERROR:  uncaughtError Error: Calling js method destroyItem failed
JS: Error: java.lang.IllegalStateException: Cannot detach Fragment attached to a different FragmentManager. Fragment FragmentBase_vendor_170467_32_TabFragmentImplementation{62f5ecc (932f1a79-324f-4a25-bddc-b07dbc229487) id=0x12 android:viewpager:18:0} is already attached to a FragmentManager.
JS:     androidx.fragment.app.BackStackRecord.detach(BackStackRecord.java:221)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1109)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1089)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1081)
JS:     com.tns.gen.androidx.viewpager.widget.PagerAdapter_vendor_170498_32_FragmentPagerAdapter.destroyItem(PagerAdapter_vendor_170498_32_FragmentPagerAdapter.java:45)
JS:     androidx.viewpager.widget.ViewPager.dataSetChanged(ViewPager.java:1047)
JS:     androidx.viewpag...
JS: ---------------------------------------------------
JS: ****************** ERROR ****************** 
JS: 
JS:     Message: Calling js method destroyItem failed
JS: Error: java.lang.IllegalStateException: Cannot detach Fragment attached to a different FragmentManager. Fragment FragmentBase_vendor_170467_32_TabFragmentImplementation{62f5ecc (932f1a79-324f-4a25-bddc-b07dbc229487) id=0x12 android:viewpager:18:0} is already attached to a FragmentManager.
JS:     androidx.fragment.app.BackStackRecord.detach(BackStackRecord.java:221)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1109)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1089)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1081)
JS:     com.tns.gen.androidx.viewpager.widget.PagerAdapter_vendor_170498_32_FragmentPagerAdapter.destroyItem(PagerAdapter_vendor_170498_32_FragmentPagerAdapter.java:45)
JS:     androidx.viewpager.widget.ViewPager.dataSetChanged(ViewPager.j...

```

**Comment by bradmartin** [comment]
Should be remedied by switching to segmented-bar on the activity page. Will monitor with changes incoming later on activity-tab

**Comment by p-ranav** [comment]
Pretty sure this can be closed now. I don't see this anymore.

**Comment by bradmartin** [comment]
Agree 💯 the segmented bar on activity-tab should have closed it 👍
