### ISSUE TITLE
Max Speed bottomsheet in Profile settings page does not open

### ISSUE THREAD

**Issue by p-ranav** [Max-Mobility/permobil-client#349]
```bash
JS: params {}
JS: ERROR Error: Uncaught (in promise): TypeError: Cannot set property 'closeCallback' of undefined
JS: TypeError: Cannot set property 'closeCallback' of undefined
JS:     at StackLayout.push.../node_modules/nativescript-material-bottomsheet/bottomsheet-common.js.ViewWithBottomSheetBase._showNativeBottomSheet (file:///node_modules/nativescript-material-bottomsheet/bottomsheet-common.js:56:0)
JS:     at StackLayout.push.../node_modules/nativescript-material-bottomsheet/bottomsheet.js.ViewWithBottomSheet._showNativeBottomSheet (file:///node_modules/nativescript-material-bottomsheet/bottomsheet.js:123:0)
JS:     at StackLayout.derivedCtor.<computed> [as _showNativeBottomSheet] (file:///node_modules/nativescript-material-core/core.common.js:41:0)
JS:     at GridLayout.push.../node_modules/nativescript-material-bottomsheet/bottomsheet-common.js.ViewWithBottomSheetBase.showBottomSheet (file:///node_modules/nativescript-material-bottomsheet/bottomsheet-common.js:91:0)
JS:     at file:///node_modules/nativescript-material-bottomsheet/angular/bottomsheet.service.js:34:0
JS:     at ZoneDe...
```

**Comment by bradmartin** [comment]
closed via https://github.com/Max-Mobility/permobil-client/commit/b2298862cdc21bf9a9b26fec081df6a3fa744da8
