### ISSUE TITLE
Tapping Switch Control Max Speed in Profile settings page does nothing 

### ISSUE THREAD

**Issue by p-ranav** [Max-Mobility/permobil-client#350]
```bash
JS: DEBUG:  User tapped: switch-control-max-speed
JS: ---------------------------------------------------
JS: params {}
JS: ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'value: undefined'. Current value: 'value: NaN'.
JS: ERROR CONTEXT {
JS:   "view": {
JS:     "def": {
JS:       "nodeFlags": 737297,
JS:       "rootNodeFlags": 1,
JS:       "nodeMatchedQueries": 0,
JS:       "flags": 0,
JS:       "nodes": [
JS:         {
JS:           "nodeIndex": 0,
JS:           "parent": null,
JS:           "renderParent": null,
JS:           "bindingIndex": 0,
JS:           "outputIndex": 0,
JS:           "checkIndex": 0,
JS:           "flags": 1,
JS:           "childFlags": 737297,
JS:           "directChildFlags": 1,
JS:           "childMatchedQueries": 0,
JS:           "matchedQueries": {},
JS:           "matchedQueryIds": 0,
JS:           "references": {},
JS:           "ngContentIndex": null,
JS:           "childCount": 14,
JS:           "bindings": [],
JS:           "bindingFlags": 0,
JS:           "outputs": [],
JS:           "element": {
JS:             "ns": "",
JS:             "name": "StackLayout",
JS:             "attrs": [
JS:               [
JS:                 "",
JS:                 "class",
JS:                 "bottom-sheet-layout"
JS:               ]
JS:             ],
JS:             "template": null,
JS:             "componentProvider": null,
JS:             "componentView"...
JS: ERROR Error: Uncaught (in promise): TypeError: Cannot set property 'closeCallback' of undefined
JS: TypeError: Cannot set property 'closeCallback' of undefined
JS:     at StackLayout.push.../node_modules/nativescript-material-bottomsheet/bottomsheet-common.js.ViewWithBottomSheetBase._showNativeBottomSheet (file:///node_modules/nativescript-material-bottomsheet/bottomsheet-common.js:56:0)
JS:     at StackLayout.push.../node_modules/nativescript-material-bottomsheet/bottomsheet.js.ViewWithBottomSheet._showNativeBottomSheet (file:///node_modules/nativescript-material-bottomsheet/bottomsheet.js:123:0)
JS:     at StackLayout.derivedCtor.<computed> [as _showNativeBottomSheet] (file:///node_modules/nativescript-material-core/core.common.js:41:0)
JS:     at GridLayout.push.../node_modules/nativescript-material-bottomsheet/bottomsheet-common.js.ViewWithBottomSheetBase.showBottomSheet (file:///node_modules/nativescript-material-bottomsheet/bottomsheet-common.js:91:0)
JS:     at file:///node_modules/nativescript-material-bottomsheet/angular/bottomsheet.service.js:34:0
JS:     at ZoneDe...
```

**Comment by bradmartin** [comment]
Just for reference, wasn't closeCallback as that's not set with the angular module of the plugin via the API. It's handled internally in the service if I recall.

This was just not configured in the tap event switch statement to open the slider for the config setting.
