### ISSUE TITLE
ListPickers are crashing in Android 10.0

### ISSUE THREAD

**Issue by p-ranav** [Max-Mobility/permobil-client#362]
List pickers (in both profile-tab and profile-settings) are crashing in Android 10.0 - *verified on Pixel 3 XL emulator and @finger563's Pixel 2 XL*. 

Works fine on Huawei Mate 20 X running Android 9.0.

![Screenshot from 2019-09-26 08-45-05](https://user-images.githubusercontent.com/8450091/65693552-14035b00-e03a-11e9-88a5-57be404c09a9.png)

**Comment by p-ranav** [comment]
Related from a week ago: https://github.com/NativeScript/NativeScript/issues/7844

**Comment by p-ranav** [comment]
```bash
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onStart failed
System.err: TypeError: this.nativeView.getTextColor is not a function
System.err: 
System.err: StackTrace:
System.err:     push.../node_modules/tns-core-modules/ui/list-picker/list-picker.js.ListPicker.<computed>(file:///node_modules/tns-core-modules/ui/list-picker/list-picker.js:139:0)
System.err:     at applyAllNativeSetters(file:///node_modules/tns-core-modules/ui/core/properties/properties.js:1060:0)
System.err:     at initNativeView(file:///node_modules/tns-core-modules/ui/core/properties/properties.js:990:0)
System.err:     at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.onResumeNativeUpdates(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:628:0)
System.err:     at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._resumeNativeUpdates(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:273:0)
System.err:     at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.onLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:232:0)
System.err:     at push.../node_modules/tns-core-modules/ui/core/view/view.js.View.onLoaded(file:///node_modules/tns-core-modules/ui/core/view/view.js:246:0)
System.err:     at (file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:75)
System.err:     at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:305:0)
System.err:     at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.callLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:0)
System.err:     at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.loadView(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:440:0)
System.err:     at (file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:234:0)
System.err:     at push.../node_modules/tns-core-modules/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView(file:///node_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:0)
System.err:     at push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild(file:///node_modules/tns-core-modules/ui/core/view/view-common.js:1010:0)
System.err:     at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.onLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:233:0)
System.err:     at push.../node_modules/tns-core-modules/ui/core/view/view.js.View.onLoaded(file:///node_modules/tns-core-modules/ui/core/view/view.js:246:0)
System.err:     at (file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:75)
System.err:     at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:305:0)
System.err:     at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.callLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:0)
System.err:     at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.loadView(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:440:0)
System.err:     at (file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:234:0)
System.err:     at push.../node_modules/tns-core-modules/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView(file:///node_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:0)
System.err:     at push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild(file:///node_modules/tns-core-modules/ui/core/view/view-common.js:1010:0)
System.err:     at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.onLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:233:0)
System.err:     at push.../node_modules/tns-core-modules/ui/core/view/view.js.View.onLoaded(file:///node_modules/tns-core-modules/ui/core/view/view.js:246:0)
System.err:     at (file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:75)
System.err:     at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:305:0)
System.err:     at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.callLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:0)
System.err:     at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.loadView(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:440:0)
System.err:     at (file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:234:0)
System.err:     at push.../node_modules/tns-core-modules/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView(file:///node_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:0)
System.err:     at push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild(file:///node_modules/tns-core-modules/ui/core/view/view-common.js:1010:0)
System.err:     at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.onLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:233:0)
System.err:     at push.../node_modules/tns-core-modules/ui/core/view/view.js.View.onLoaded(file:///node_modules/tns-core-modules/ui/core/view/view.js:246:0)
System.err:     at (file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:75)
System.err:     at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:305:0)
System.err:     at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.callLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:0)
System.err:     at BottomSheetDialogFragmentImpl.onStart(file:///node_modules/nativescript-material-bottomsheet/bottomsheet.js:82:0)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1209)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1096)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1083)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1063)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1055)
System.err:     at com.tns.gen.com.google.android.material.bottomsheet.BottomSheetDialogFragment_vendor_97682_32_BottomSheetDialogFragmentImpl.onStart(BottomSheetDialogFragment_vendor_97682_32_BottomSheetDialogFragmentImpl.java:31)
System.err:     at androidx.fragment.app.Fragment.performStart(Fragment.java:2650)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:908)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1228)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1293)
System.err:     at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
System.err:     at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2066)
System.err:     at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1856)
System.err:     at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1811)
System.err:     at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1717)
System.err:     at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
System.err:     at android.os.Handler.handleCallback(Handler.java:883)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
System.err:     at android.os.Looper.loop(Looper.java:214)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7356)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
JS: ERROR:  uncaughtError Error: Calling js method onStart failed
JS: TypeError: this.nativeView.getTextColor is not a function
JS: ---------------------------------------------------
JS: ****************** ERROR ****************** 
JS: 
JS:     Message: Calling js method onStart failed
JS: TypeError: this.nativeView.getTextColor is not a function 
JS: 
JS:     Stack: Error: Calling js method onStart failed
JS: TypeError: this.nativeView.getTextColor is not a function
```

**Comment by p-ranav** [comment]
Even [this](https://github.com/Max-Mobility/permobil-client/commit/0e39fb0103585d5e0a768fdeefc1445292e1251e#diff-58003330e87dfd39912f01ed042545f4) commit from 9 days ago throws this error. In this case, I can't even enter the Profile page..

**Comment by p-ranav** [comment]
Fixed after updating android sdk and build tools to latest version.
