### ISSUE TITLE
Error connecting pushtracker device to app

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#377]
```
 PushTracker.model Sending Command::SetTime::[object Object] to 88:6B:0F:78:41:7F 
JS: 
JS: Sentry Breadcrumb:  {
JS:   "message": "[TabsComponent] distance_event received from PushTracker",
JS:   "category": "Info",
JS:   "level": "info"
JS: }
JS: ---------------------------------------------------
JS: ****************** ERROR ****************** 
JS: 
JS:     Message: stream.toPromise is not a function 
JS: 
JS:     Stack: TypeError: stream.toPromise is not a function
JS:     at SmartDriveUsageService.<anonymous> (file:///src/app/services/smartdrive-usage.service.ts:36:22)
JS:     at step (file:///node_modules/tslib/tslib.es6.js:99:0)
JS:     at Object.next (file:///node_modules/tslib/tslib.es6.js:80:44)
JS:     at file:///node_modules/tslib/tslib.es6.js:73:0
JS:     at new ZoneAwarePromise (file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:902:0)
JS:     at __awaiter (file:///node_modules/tslib/tslib.es6.js:69:0)
JS:     at SmartDriveUsageService.module.exports.push../app/services/smartdrive-usage.service.ts.SmartDriveUsageService.saveDailyUsageFromPushTracker (file:///data/data/com.permobil.pushtracker/files/app/bundle.js:101565:16)
JS:     at TabsComponent.module.exports.push../app/modules/tabs/tabs.component.ts....
JS: ****************** ERROR ****************** 
JS: 
JS:     Message: [TabsComponent] Failed to save Distance from PushTracker in Kinvey 
JS: 
JS:     Stack: Error: [TabsComponent] Failed to save Distance from PushTracker in Kinvey
JS:     at file:///src/app/modules/tabs/tabs.component.ts:348:40 [<root>]
JS:     at file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:883:0 [<root>]
JS:     at drainMicroTaskQueue (file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:595:0) [<root>]
JS: Sentry Breadcrumb:  {
JS:   "message": "[TabsComponent] daily_info_event received from PushTracker",
JS:   "category": "Info",
JS:   "level": "info"
JS: }
JS: ---------------------------------------------------
JS: ****************** ERROR ****************** 
JS: 
JS:     Message: stream.toPromise is not a function 
JS: 
JS:     Stack: TypeError: stream.toPromise is not a function
JS:     at ActivityService.<anonymous> (file:///src/app/services/activity.service.ts:33:22)
JS:     at step (file:///node_modules/tslib/tslib.es6.js:99:0)
JS:     at Object.next (file:///node_modules/tslib/tslib.es6.js:80:44)
JS:     at file:///node_modules/tslib/tslib.es6.js:73:0
JS:     at new ZoneAwarePromise (file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:902:0)
JS:     at __awaiter (file:///node_modules/tslib/tslib.es6.js:69:0)
JS:     at ActivityService.module.exports.push../app/services/activity.service.ts.ActivityService.saveDailyActivityFromPushTracker (file:///data/data/com.permobil.pushtracker/files/app/bundle.js:99809:16)
JS:     at TabsComponent.module.exports.push../app/modules/tabs/tabs.component.ts.TabsComponent.onDailyInfoEve...
JS: 
JS: 
JS:  PushTracker.model Sending Command::DistanceRequest::undefined to 88:6B:0F:78:41:7F 
JS: 
JS: Sentry Breadcrumb:  {
JS:   "message": "[TabsComponent] Distance data requested from PushTracker",
JS:   "category": "Info",
JS:   "level": "info"
JS: }
JS: ---------------------------------------------------
JS: ****************** ERROR ****************** 
JS: 
JS:     Message: [TabsComponent] Failed to save DailyInfo from PushTracker in Kinvey 
JS: 
JS:     Stack: Error: [TabsComponent] Failed to save DailyInfo from PushTracker in Kinvey
JS:     at file:///src/app/modules/tabs/tabs.component.ts:310:40 [<root>]
JS:     at file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:883:0 [<root>]
JS:     at drainMicroTaskQueue (file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:595:0) [<root>]


```

**Comment by finger563** [comment]
Looks like it's related to the change we made to the datastore type to be `AUTO` - per [the docs](https://devcenter.kinvey.com/nativescript/guides/datastore#Fetching):

> For the Auto data store type, the Kinvey JavaScript library uses promises to return data on find operations.
> 
> For the Cache, Network, and Sync data store types, the Kinvey JavaScript library uses the observable pattern to return data on find operations. APIs that fetch data require the application to register a subscriber that gets invoked when data is available. We use Observables to accomplish this.
```
