### ISSUE TITLE
Exception: Cannot read property 'notifyCharacteristicChanged' of undefined

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#43]
From EvalApp created by [finger563](https://github.com/finger563): PushTracker/EvalApp#379  

https://sentry.io/organizations/maxmobility/issues/1075898136/?referrer=github_plugin

```
Throwable: TypeError: Cannot read property 'notifyCharacteristicChanged' of undefined
    at file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-bluetooth/android/android_main.js:725:42
    at new ZoneAwarePromise (file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:902:29)
    at notify_1 (file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-bluetooth/android/android_main.js:699:24)
    at Bluetooth.notifyCentrals (file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-bluetooth/android/android_main.js:737:16)
    at BluetoothService.sendToPushTrackers (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@maxmobility/mobile/core/services/bluetooth.service.js:500:32)
    at PushTracker.sendPacket (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@maxmobility/core/models/pushtracker.model.js:468:39)
    at PushTracker.sendSettings (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@maxmobility/core/models/pushtracker.model.js:499:21)
    at sendSettings (file:///data/data/com.permobil.smarteval/files/app/modules/pairing/pairing.component.js:221:32)
    at retry (file:///data/data/com.permobil.smarteval/files/app/modules/pairing/pairing.component.js:203:20)
    at PairingComponent.onSaveSettings (file:///data/data/com.permobil.smarteval/files/app/modules/pairing/pairing.component.js:231:16)
    at Object.eval [as handleEvent] (ng:///PairingModule/PairingComponent.ngfactory.js:199:31)
    at handleEvent (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js:23030:45)
    at callWithDebugContext (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js:24100:29)
    at Object.debugHandleEvent [as handleEvent] (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js:23827:16)
    at dispatchEvent (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js:20479:29)
    at com.tns.Runtime.callJSMethodNative(Runtime.java)
    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
    at com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
    at com.tns.Runtime.callJSMethod(Runtime.java:987)
    at com.tns.Runtime.callJSMethod(Runtime.java:967)
...
(14 additional frame(s) were not displayed)

Exception: Cannot read property 'notifyCharacteristicChanged' of undefined
    at com.tns.Runtime.callJSMethodNative(Runtime.java)
    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
    at com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
    at com.tns.Runtime.callJSMethod(Runtime.java:987)
    at com.tns.Runtime.callJSMethod(Runtime.java:967)
...
(14 additional frame(s) were not displayed)

Cannot read property 'notifyCharacteristicChanged' of undefined
```

**Comment by finger563** [comment]
appears they were trying to save settings 
![IMG_0671](https://user-images.githubusercontent.com/213467/59714441-4a2d7500-91d7-11e9-9bf4-a458a4bb6d88.jpg)
